/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import app.Cliente;
import java.io.IOException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.LinkedList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import model.Bilhete;

/**
 *
 * @author User
 */
public class MenuUsuario extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuario
     */
    LinkedList<Bilhete> meusBilhetes = new LinkedList<>();
    DefaultListModel modelo = new DefaultListModel();
    public static int companhia = 0;
    public static MenuUsuario menu;
    public MenuUsuario() throws IOException, ClassNotFoundException, RemoteException, NotBoundException {
        initComponents();
        adicionarElementos();
    }
    
    public void adicionarElementos() throws IOException, ClassNotFoundException, RemoteException, NotBoundException {
        Cliente c = new Cliente();
        meusBilhetes = c.listarBilhetesComprados(TelaLogin.loginAux, TelaInicial.ip_a, TelaInicial.porta_a);
        if(meusBilhetes.isEmpty()){
            meusBilhetes = c.listarBilhetesComprados(TelaLogin.loginAux, TelaInicial.ip_b, TelaInicial.porta_b);
            if(meusBilhetes.isEmpty()){
                meusBilhetes = c.listarBilhetesComprados(TelaLogin.loginAux, TelaInicial.ip_c, TelaInicial.porta_c);
            }
        }
        if(!meusBilhetes.isEmpty()){
            System.out.println("Os bilhetes existem");
            listaBilhetes.removeAll();
            if(!meusBilhetes.isEmpty()){
                for(int i = 0; i < meusBilhetes.size(); i++){
                    modelo.addElement("Código: " + meusBilhetes.get(i).getId()
                                    + "| Origem: " + meusBilhetes.get(i).getOrigem()
                                    + "| Destino: " + meusBilhetes.get(i).getDestino()
                                    + "| Preço: R$" + meusBilhetes.get(i).getPreco()
                                    + "| Data: " + meusBilhetes.get(i).getData() + " # " + meusBilhetes.get(i).getHorario_voo()
                    );
                }
            }    
        }
        listaBilhetes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        norte = new javax.swing.JButton();
        centro = new javax.swing.JButton();
        sul = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaBilhetes = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu do Usuário");
        setResizable(false);

        norte.setText("Companhia Norte - Nordeste");
        norte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                norteActionPerformed(evt);
            }
        });

        centro.setText("Companha Centro-Oeste");
        centro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                centroActionPerformed(evt);
            }
        });

        sul.setText("Companhia Sul - Suldeste");
        sul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sulActionPerformed(evt);
            }
        });

        listaBilhetes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaBilhetes);

        jLabel1.setText("Meus Bilhetes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(norte)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                        .addComponent(centro, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(sul, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(norte)
                    .addComponent(centro)
                    .addComponent(sul))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void norteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_norteActionPerformed
        companhia = 1;
        try {
            this.setVisible(false);
            ListarBilhetes.listarBilhetes = new ListarBilhetes();
            ListarBilhetes.listarBilhetes.setVisible(true);
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(MenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_norteActionPerformed

    private void centroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_centroActionPerformed
        companhia = 2;
        try {
            this.setVisible(false);
            ListarBilhetes.listarBilhetes = new ListarBilhetes();
            ListarBilhetes.listarBilhetes.setVisible(true);
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(MenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_centroActionPerformed

    private void sulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sulActionPerformed
        companhia = 3;
        try {
            this.setVisible(false);
            ListarBilhetes.listarBilhetes = new ListarBilhetes();
            ListarBilhetes.listarBilhetes.setVisible(true);
        } catch (RemoteException | NotBoundException ex) {
            Logger.getLogger(MenuUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_sulActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton centro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaBilhetes;
    private javax.swing.JButton norte;
    private javax.swing.JButton sul;
    // End of variables declaration//GEN-END:variables
}
